### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by euank** [andrenth/go-fdpass#1]
Hey, thanks for the nice little library/code for doing all the sendmsg juggling needed for fd sending (even if it predates go1 and doesn't compile now as is).

Is there any chance you could include a license file or comment so others can feel comfortable deriving any further code from this, or otherwise using it?

Thanks!

**Comment by andrenth** [comment]
Hey! I didn't even remember this repo existed :smiley: 

I went ahead and adapted the code so that it builds on modern Go, and added a license file, but I moved the repository to Gitlab:

https://gitlab.com/andrenathan/go/fdpass

Cheers!
